# .github/workflows/deploy.yml

name: Deploy Frontend

# prod 브랜치에 push 될 때만 실행
on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 프로젝트에 맞는 버전으로 수정
          cache: 'npm'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 프로덕션 빌드
      - name: Build project
        run: npm run build

      # 5. 빌드된 파일을 서버로 복사
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"  # 'dist/*' 등 빌드 폴더 경로에 맞게 수정
          target: "/var/www/hwajeon_main_page" # 실제 파일이 서빙될 서버 경로로 수정
          strip_components: 1 # source 경로의 최상위 폴더(build)를 제외하고 내용물만 복사
